//! The menu-bar tray: icon, status menu, and the hide-to-tray window
//! behavior in `lib.rs`'s `on_window_event`.
//!
//! `menu_model` is a pure function from the scheduler's shared state, plus
//! whether a catalog is selected (which `SchedulerStateOutcome` cannot
//! distinguish from "not ticked yet" — see the Task 14 amendment in
//! `docs/superpowers/plans/2026-08-26-phase7e-alwayson-e2e-doctor.md`), to a
//! plain [`MenuModel`]. Tauri's menu objects are built FROM that model in
//! `build_menu`, a thin untested shim — the same philosophy `commands.rs`
//! follows for its `*_impl` functions: logic stays testable, the Tauri glue
//! does not.
use crate::commands::{AppState, selected_catalog};
use crate::indexer::{SchedulerShared, SchedulerState, set_throttle_impl};
use majestical_services::autopilot::{
    HoldReason, PowerSource, SchedulerDecision, ThrottleOverride,
};
use std::sync::PoisonError;
use tauri::menu::{CheckMenuItemBuilder, Menu, MenuBuilder, MenuItemBuilder};
use tauri::tray::TrayIconBuilder;
use tauri::{AppHandle, Emitter, Manager};

/// The tray icon's id — `refresh` looks the tray back up by this id to
/// rebuild its menu.
const TRAY_ID: &str = "main";

/// The Tauri event `App.svelte` listens for to select the Settings surface,
/// fired by "Health…" and the attention line.
const NAVIGATE_SETTINGS_EVENT: &str = "navigate-settings";

/// The attention line's text, shared by `build_menu` (the menu item) and
/// the tests (pinning it) — present iff `MenuModel::attention` is.
const ATTENTION_LINE: &str = "Last batch failed — open Health…";

/// The tray's four macOS template icons (monochrome — only the alpha
/// channel is used; RGB is ignored, per `icon_as_template`), generated by
/// the `tray-icons` recipe in the root justfile and committed under
/// `icons/tray/`. The `@2x` (44×44) files are the ones loaded: `tray_icon`
/// 0.24's macOS `set_icon` builds the `NSImage` from the PNG bytes and then
/// sizes it to 18 points tall regardless of pixel dimensions, so a 44 px
/// image renders at 18 pt with 2× density on a Retina display and is
/// downsampled on a 1× one — no `HiDPI` plumbing of our own. (The phase 7E
/// note that a `@2x` file "would render twice the intended size" was wrong
/// for this library version.) The `@1x` (22×22) files are still generated
/// by the same recipe; nothing loads them.
const ICON_IDLE: &[u8] = include_bytes!("../icons/tray/idle@2x.png");
const ICON_INDEXING: &[u8] = include_bytes!("../icons/tray/indexing@2x.png");
const ICON_PAUSED: &[u8] = include_bytes!("../icons/tray/paused@2x.png");
/// The idle look plus a small solid dot badge, standing in for the
/// mockup's amber attention tint — a macOS template icon is rendered
/// monochrome by the system (only its alpha channel is used), so no tint
/// color survives from the source PNG regardless of what is drawn into it.
const ICON_ATTENTION: &[u8] = include_bytes!("../icons/tray/attention@2x.png");

/// The tray icon's current look. `Attention` replaces whichever of the
/// other three a decision would otherwise select, computed once in
/// `menu_model` — see [`ICON_ATTENTION`] for why a badge substitutes for
/// the mockup's tint rather than coloring one of the other three.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayLook {
    Idle,
    Indexing,
    Paused,
    Attention,
}

impl TrayLook {
    /// This look's embedded PNG bytes. Exhaustive, so a new variant cannot
    /// ship without an icon to render it with.
    #[must_use]
    fn bytes(self) -> &'static [u8] {
        match self {
            TrayLook::Idle => ICON_IDLE,
            TrayLook::Indexing => ICON_INDEXING,
            TrayLook::Paused => ICON_PAUSED,
            TrayLook::Attention => ICON_ATTENTION,
        }
    }
}

/// Decodes a look's embedded PNG into the `Image` `TrayIconBuilder`/
/// `TrayIcon::set_icon` need. Thin and untested — `TrayLook::bytes` and
/// `menu_model` carry the logic; decoding an embedded, always-valid PNG
/// cannot fail in practice, but the `?` still routes a hypothetical decode
/// error through the same `tauri::Result` the tray's build/refresh calls
/// return.
fn icon_image(look: TrayLook) -> tauri::Result<tauri::image::Image<'static>> {
    tauri::image::Image::from_bytes(look.bytes())
}

/// What the tray menu shows, computed from the scheduler's shared state and
/// whether a catalog is selected. Pure and no-I/O — see the module doc.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MenuModel {
    /// The status line(s) at the top of the menu: one line normally, two
    /// when a run-low names its reason ("On battery"/"Power source
    /// unknown") or a low-power-mode hold has pending work to report.
    pub status_lines: Vec<String>,
    /// Whether the attention line ([`ATTENTION_LINE`]) shows, and the icon
    /// is `TrayLook::Attention` — present iff `last_error` is.
    pub attention: bool,
    /// The checked radio item.
    pub throttle: ThrottleOverride,
    /// Whether the radio group responds to clicks — false with no catalog
    /// selected, since there is nothing to throttle.
    pub throttle_enabled: bool,
    pub look: TrayLook,
}

/// "1 item pending" / "{n} items pending" — the tray's copy is new, so it
/// pluralizes correctly from day one rather than copying the app's older
/// "1 items" pattern (see the mockup's pluralization note).
fn pending_line(n: u64) -> String {
    if n == 1 {
        "1 item pending".to_string()
    } else {
        format!("{n} items pending")
    }
}

/// One `RunLow` state's status line(s): "Indexing slowly — {n} items
/// pending", plus a second line naming the power reason ONLY when Auto
/// chose Low — under the Low override the second line would be redundant
/// with the operator's own choice.
fn run_low_lines(state: &SchedulerShared) -> Vec<String> {
    let mut lines = vec![format!(
        "Indexing slowly — {}",
        pending_line(state.pending_items)
    )];
    if state.throttle == ThrottleOverride::Auto {
        match state.power.source {
            PowerSource::Battery => lines.push("On battery".to_string()),
            PowerSource::Unknown => lines.push("Power source unknown".to_string()),
            PowerSource::Ac => {}
        }
    }
    lines
}

/// The status line(s) and icon look a catalog-selected scheduler state
/// renders as. Split out of `menu_model` to keep each function under the
/// workspace's complexity limit — this is the decision match, `menu_model`
/// is the no-catalog check plus the attention override.
fn status_and_look(state: &SchedulerShared) -> (Vec<String>, TrayLook) {
    match state.last_decision {
        None => (vec!["Starting…".to_string()], TrayLook::Idle),
        Some(SchedulerDecision::Hold(HoldReason::NoPendingWork)) => {
            (vec!["Idle".to_string()], TrayLook::Idle)
        }
        Some(SchedulerDecision::RunFull) => (
            vec![format!("Indexing — {}", pending_line(state.pending_items))],
            TrayLook::Indexing,
        ),
        Some(SchedulerDecision::RunLow) => (run_low_lines(state), TrayLook::Indexing),
        Some(SchedulerDecision::Hold(HoldReason::Paused)) => {
            // Pending count deliberately omitted: the user asked for quiet.
            (vec!["Paused".to_string()], TrayLook::Paused)
        }
        Some(SchedulerDecision::Hold(HoldReason::LowPowerMode)) => {
            let mut lines = vec!["Paused (Low Power Mode)".to_string()];
            if state.pending_items > 0 {
                lines.push(pending_line(state.pending_items));
            }
            (lines, TrayLook::Paused)
        }
    }
}

/// `Attention` overrides `base` when `attention` is set — the one place
/// that override happens, shared by `menu_model`'s two struct literals.
fn resolve_look(base: TrayLook, attention: bool) -> TrayLook {
    if attention { TrayLook::Attention } else { base }
}

/// Computes the tray menu's model. `catalog_selected` is the wire gap the
/// Task 14 amendment resolves by taking it as a second input read from
/// `AppState` at rebuild time, rather than adding a field to
/// `SchedulerStateOutcome`. See `tray-menu.html`'s "Status line ← wire
/// mapping" table for the exact strings this pins.
#[must_use]
pub fn menu_model(state: &SchedulerShared, catalog_selected: bool) -> MenuModel {
    let attention = state.last_error.is_some();

    if !catalog_selected {
        return MenuModel {
            status_lines: vec!["No catalog selected".to_string()],
            attention,
            throttle: state.throttle,
            throttle_enabled: false,
            look: resolve_look(TrayLook::Idle, attention),
        };
    }

    let (status_lines, base_look) = status_and_look(state);
    MenuModel {
        status_lines,
        attention,
        throttle: state.throttle,
        throttle_enabled: true,
        look: resolve_look(base_look, attention),
    }
}

/// Builds the Tauri menu the tray shows from a [`MenuModel`]. Thin and
/// untested — [`menu_model`] carries the logic. Status lines are
/// non-interactive; the attention line, when present, is clickable and does
/// the same thing "Health…" does.
fn build_menu(app: &AppHandle, model: &MenuModel) -> tauri::Result<Menu<tauri::Wry>> {
    let mut builder = MenuBuilder::new(app);
    for (i, line) in model.status_lines.iter().enumerate() {
        builder = builder.item(
            &MenuItemBuilder::new(line)
                .id(format!("status-{i}"))
                .enabled(false)
                .build(app)?,
        );
    }
    if model.attention {
        builder = builder.item(
            &MenuItemBuilder::new(ATTENTION_LINE)
                .id("attention")
                .build(app)?,
        );
    }
    builder = builder.separator();
    for (id, label, throttle) in [
        ("throttle-auto", "Auto", ThrottleOverride::Auto),
        ("throttle-paused", "Paused", ThrottleOverride::Paused),
        ("throttle-low", "Low", ThrottleOverride::Low),
        ("throttle-full", "Full", ThrottleOverride::Full),
    ] {
        builder = builder.item(
            &CheckMenuItemBuilder::new(label)
                .id(id)
                .checked(model.throttle == throttle)
                .enabled(model.throttle_enabled)
                .build(app)?,
        );
    }
    builder
        .separator()
        .item(
            &MenuItemBuilder::new("Open Majestical")
                .id("open")
                .build(app)?,
        )
        .item(&MenuItemBuilder::new("Health…").id("health").build(app)?)
        .separator()
        .item(
            &MenuItemBuilder::new("Quit Majestical")
                .id("quit")
                .build(app)?,
        )
        .build()
}

/// Shows and focuses the main window, restoring the Dock icon on macOS —
/// what "Open Majestical" and the first step "Health…" and the attention
/// line take before navigating.
fn show_window(app: &AppHandle) {
    if let Some(window) = app.get_webview_window("main") {
        // Every call here can fail only if the window is mid-teardown (a
        // race with the app quitting) or the platform refuses focus for a
        // reason outside this app's control; either way there is nothing
        // to retry and no log sink to report it to, so the failure is
        // silently absorbed rather than surfaced.
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
    // Same rationale: a failed activation-policy switch leaves the Dock
    // icon in whatever state it was already in, a cosmetic inconsistency
    // rather than a broken window.
    #[cfg(target_os = "macos")]
    let _ = app.set_activation_policy(tauri::ActivationPolicy::Regular);
}

/// Applies a throttle override the same way `set_throttle` does, then
/// rebuilds the menu so the checked radio moves immediately rather than
/// waiting for the next tick.
fn apply_throttle(app: &AppHandle, throttle: ThrottleOverride) {
    let state = app.state::<SchedulerState>();
    // The returned `SchedulerStateOutcome` is the same shape `set_throttle`
    // hands the Settings surface, but nothing here has anywhere to put it —
    // `refresh` right after reads the state fresh from `SchedulerState`
    // itself, not from this return value.
    let _ = set_throttle_impl(&state, throttle);
    refresh(app);
}

fn handle_menu_event(app: &AppHandle, id: &str) {
    match id {
        "throttle-auto" => apply_throttle(app, ThrottleOverride::Auto),
        "throttle-paused" => apply_throttle(app, ThrottleOverride::Paused),
        "throttle-low" => apply_throttle(app, ThrottleOverride::Low),
        "throttle-full" => apply_throttle(app, ThrottleOverride::Full),
        "open" => show_window(app),
        "health" | "attention" => {
            show_window(app);
            // No listener (a webview that has not mounted yet, or is
            // reloading) is not an error: `App.svelte`'s effect
            // re-subscribes on its own, and the operator can click
            // "Health…" again if the surface never switches.
            let _ = app.emit(NAVIGATE_SETTINGS_EVENT, ());
        }
        // The scheduler never holds a transaction open across a tick: a
        // batch is one per-kind-capped run (`indexer::BATCH_LIMIT` items per
        // kind, seconds to a minute), and the loop sleeps between batches —
        // there is nothing an immediate exit here could tear.
        "quit" => app.exit(0),
        _ => {}
    }
}

/// Builds the tray icon and its initial menu. Called once from `setup`.
///
/// No left-click handler: with `show_menu_on_left_click` at Tauri's
/// default (true), macOS runs the menu tracking loop synchronously on
/// mouse-down and no mouse-up event ever reaches an `on_tray_icon_event`
/// handler here — "Open Majestical" is the only way in from the tray.
///
/// # Errors
/// Returns an error if the idle icon's embedded PNG fails to decode, or if
/// the Tauri runtime refuses to build the menu or the tray icon itself.
pub(crate) fn build_tray(app: &AppHandle) -> tauri::Result<()> {
    let model = current_model(app);
    let menu = build_menu(app, &model)?;
    let icon = icon_image(model.look)?;
    TrayIconBuilder::with_id(TRAY_ID)
        .icon(icon)
        .icon_as_template(true)
        .menu(&menu)
        .on_menu_event(|app, event| handle_menu_event(app, event.id().as_ref()))
        .build(app)?;
    Ok(())
}

/// Reads the scheduler's shared state and whether a catalog is selected,
/// and computes this instant's [`MenuModel`].
fn current_model(app: &AppHandle) -> MenuModel {
    let scheduler = app.state::<SchedulerState>();
    let app_state = app.state::<AppState>();
    let catalog_selected = selected_catalog(&app_state).is_some();
    let shared = scheduler.0.read().unwrap_or_else(PoisonError::into_inner);
    menu_model(&shared, catalog_selected)
}

/// Rebuilds the tray's menu and icon from the scheduler's current state.
/// Called at the end of every scheduler tick and right after a throttle
/// change, so the status line and icon look are at most one tick stale.
/// Re-decodes the icon on every call rather than tracking whether the look
/// changed — a 22×22 PNG is cheap enough that the tracking would cost more
/// than it saves.
pub(crate) fn refresh(app: &AppHandle) {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return;
    };
    let model = current_model(app);
    if let Ok(menu) = build_menu(app, &model) {
        // A failed `set_menu` leaves the previous menu showing — stale by
        // one tick, the same staleness a `build_menu` error above already
        // accepts, and there is nowhere to surface either failure from a
        // background thread's tick.
        let _ = tray.set_menu(Some(menu));
    }
    if let Ok(icon) = icon_image(model.look) {
        // `set_icon_with_as_template`, not a plain `set_icon`: Tauri's own
        // doc on the pair notes that `set_icon` followed by
        // `set_icon_as_template` flickers on macOS since the icon renders
        // twice — this sets both atomically instead. Its failure is
        // absorbed the same way `set_menu`'s is, just above.
        let _ = tray.set_icon_with_as_template(Some(icon), true);
    }
}

#[cfg(test)]
mod tests {
    use super::{ATTENTION_LINE, MenuModel, SchedulerShared, TrayLook, menu_model};
    use majestical_services::autopilot::{
        HoldReason, PowerSource, PowerState, SchedulerDecision, ThrottleOverride,
    };

    fn power(source: PowerSource) -> PowerState {
        PowerState {
            source,
            low_power_mode: false,
        }
    }

    fn shared(
        throttle: ThrottleOverride,
        decision: Option<SchedulerDecision>,
        source: PowerSource,
        pending_items: u64,
        last_error: Option<&str>,
    ) -> SchedulerShared {
        SchedulerShared {
            throttle,
            last_decision: decision,
            power: power(source),
            pending_items,
            failed_items: 0,
            running: false,
            last_error: last_error.map(str::to_string),
        }
    }

    #[test]
    fn status_is_starting_before_the_first_tick() {
        let state = shared(ThrottleOverride::Auto, None, PowerSource::Ac, 0, None);
        let model = menu_model(&state, true);
        assert_eq!(model.status_lines, vec!["Starting…".to_string()]);
        assert_eq!(model.look, TrayLook::Idle);
        assert!(model.throttle_enabled);
    }

    #[test]
    fn status_is_idle_on_no_pending_work() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::Hold(HoldReason::NoPendingWork)),
            PowerSource::Ac,
            0,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(model.status_lines, vec!["Idle".to_string()]);
        assert_eq!(model.look, TrayLook::Idle);
    }

    #[test]
    fn run_full_shows_indexing_with_the_pending_count() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::RunFull),
            PowerSource::Ac,
            214,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(
            model.status_lines,
            vec!["Indexing — 214 items pending".to_string()]
        );
        assert_eq!(model.look, TrayLook::Indexing);
    }

    #[test]
    fn run_low_under_auto_on_battery_names_the_reason() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::RunLow),
            PowerSource::Battery,
            214,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(
            model.status_lines,
            vec![
                "Indexing slowly — 214 items pending".to_string(),
                "On battery".to_string(),
            ]
        );
        assert_eq!(model.look, TrayLook::Indexing);
    }

    #[test]
    fn run_low_under_auto_on_unknown_power_names_the_reason() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::RunLow),
            PowerSource::Unknown,
            214,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(
            model.status_lines,
            vec![
                "Indexing slowly — 214 items pending".to_string(),
                "Power source unknown".to_string(),
            ]
        );
    }

    #[test]
    fn run_low_under_the_low_override_omits_the_second_line() {
        let state = shared(
            ThrottleOverride::Low,
            Some(SchedulerDecision::RunLow),
            PowerSource::Battery,
            214,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(
            model.status_lines,
            vec!["Indexing slowly — 214 items pending".to_string()]
        );
    }

    #[test]
    fn paused_by_you_hides_the_pending_count() {
        let state = shared(
            ThrottleOverride::Paused,
            Some(SchedulerDecision::Hold(HoldReason::Paused)),
            PowerSource::Ac,
            214,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(model.status_lines, vec!["Paused".to_string()]);
        assert_eq!(model.look, TrayLook::Paused);
    }

    #[test]
    fn low_power_mode_hold_shows_pending_count_when_nonzero() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::Hold(HoldReason::LowPowerMode)),
            PowerSource::Battery,
            214,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(
            model.status_lines,
            vec![
                "Paused (Low Power Mode)".to_string(),
                "214 items pending".to_string(),
            ]
        );
        assert_eq!(model.look, TrayLook::Paused);
    }

    #[test]
    fn low_power_mode_hold_omits_the_second_line_when_nothing_is_pending() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::Hold(HoldReason::LowPowerMode)),
            PowerSource::Battery,
            0,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(
            model.status_lines,
            vec!["Paused (Low Power Mode)".to_string()]
        );
    }

    #[test]
    fn no_catalog_selected_disables_the_throttle_group() {
        let state = shared(ThrottleOverride::Auto, None, PowerSource::Ac, 0, None);
        let model = menu_model(&state, false);
        assert_eq!(model.status_lines, vec!["No catalog selected".to_string()]);
        assert!(!model.throttle_enabled);
        assert_eq!(model.look, TrayLook::Idle);
    }

    #[test]
    fn pending_count_pluralizes_one_item_singular() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::RunFull),
            PowerSource::Ac,
            1,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(
            model.status_lines,
            vec!["Indexing — 1 item pending".to_string()]
        );
    }

    #[test]
    fn pending_count_pluralizes_two_items_plural() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::RunFull),
            PowerSource::Ac,
            2,
            None,
        );
        let model = menu_model(&state, true);
        assert_eq!(
            model.status_lines,
            vec!["Indexing — 2 items pending".to_string()]
        );
    }

    #[test]
    fn attention_is_set_iff_last_error_is() {
        let failed = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::RunFull),
            PowerSource::Ac,
            214,
            Some("disk full"),
        );
        let model = menu_model(&failed, true);
        assert!(model.attention);
        assert_eq!(model.look, TrayLook::Attention);

        let clean = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::RunFull),
            PowerSource::Ac,
            214,
            None,
        );
        let model = menu_model(&clean, true);
        assert!(!model.attention);
        assert_eq!(model.look, TrayLook::Indexing);
    }

    #[test]
    fn checked_radio_reflects_the_current_throttle() {
        for throttle in [
            ThrottleOverride::Auto,
            ThrottleOverride::Paused,
            ThrottleOverride::Low,
            ThrottleOverride::Full,
        ] {
            let state = shared(throttle, None, PowerSource::Ac, 0, None);
            let model: MenuModel = menu_model(&state, true);
            assert_eq!(model.throttle, throttle);
        }
    }

    #[test]
    fn attention_overrides_every_look() {
        for (decision, source) in [
            (
                Some(SchedulerDecision::Hold(HoldReason::NoPendingWork)),
                PowerSource::Ac,
            ),
            (Some(SchedulerDecision::RunFull), PowerSource::Ac),
            (
                Some(SchedulerDecision::Hold(HoldReason::Paused)),
                PowerSource::Ac,
            ),
            (
                Some(SchedulerDecision::Hold(HoldReason::LowPowerMode)),
                PowerSource::Battery,
            ),
        ] {
            let state = shared(
                ThrottleOverride::Auto,
                decision,
                source,
                0,
                Some("disk full"),
            );
            let model = menu_model(&state, true);
            assert_eq!(model.look, TrayLook::Attention);
        }
    }

    #[test]
    fn attention_persists_alongside_an_idle_status() {
        let state = shared(
            ThrottleOverride::Auto,
            Some(SchedulerDecision::Hold(HoldReason::NoPendingWork)),
            PowerSource::Ac,
            0,
            Some("disk full"),
        );
        let model = menu_model(&state, true);
        assert_eq!(model.status_lines, vec!["Idle".to_string()]);
        assert!(model.attention);
        assert_eq!(model.look, TrayLook::Attention);
    }

    #[test]
    fn attention_persists_alongside_a_paused_by_you_status() {
        let state = shared(
            ThrottleOverride::Paused,
            Some(SchedulerDecision::Hold(HoldReason::Paused)),
            PowerSource::Ac,
            0,
            Some("disk full"),
        );
        let model = menu_model(&state, true);
        assert_eq!(model.status_lines, vec!["Paused".to_string()]);
        assert!(model.attention);
        assert_eq!(model.look, TrayLook::Attention);
    }

    #[test]
    fn attention_persists_with_no_catalog_selected() {
        let state = shared(
            ThrottleOverride::Auto,
            None,
            PowerSource::Ac,
            0,
            Some("disk full"),
        );
        let model = menu_model(&state, false);
        assert_eq!(model.status_lines, vec!["No catalog selected".to_string()]);
        assert!(!model.throttle_enabled);
        assert!(model.attention);
        assert_eq!(model.look, TrayLook::Attention);
    }

    #[test]
    fn attention_line_text_is_pinned() {
        assert_eq!(ATTENTION_LINE, "Last batch failed — open Health…");
    }
}
